version: '3.9'

networks:
  2fauth:

services:
  2fauth:
    image: chenio/2fauth
    build: .
    ports:
      - 8010:80
    restart: unless-stopped
    environment:
      SITE_OWNER: mail@example.com
      APP_KEY: ${APP_KEY}
      APP_PORT: 80
      REDIS_HOST: 2fauth-redis
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/db/database.sqlite
    volumes:
      - ${DATA_DIR}/db:/app/db
    networks:
      - 2fauth

  2fauth-redis:
    image: redis:6.0-alpine
    restart: unless-stopped
    networks:
      - 2fauth
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
    volumes:
      - ${DATA_DIR}/redis:/data